version: "3.9"
services:
    mqcp-bot:
        build: "."
        image: mqcp-bot:latest
        container_name: mqcp-bot
        volumes:
            - type: bind 
              source: /var/log/mqcp-bot
              target: /usr/src/app/logs
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 300M
