version: "3"
services:
    mqcp-bot:
        build: "."
        image: mqcp-bot:latest
        container_name: mqcp-bot
        volumes:
            - "/var/log/mqcp-bot:/usr/src/app/logs"
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 300M
